### ISSUE TITLE
Microsoft Surface Pro is being identified as 'Android'

### ISSUE THREAD

**Issue by MrDiggles2** [WhichBrowser/Parser#74] opened 2016-08-03 22:52 UTC
I was running tests and I noticed that the Surface 3 running Edge will be identified as 'Android'. 

The user agent string is as follow:

Mozilla/5.0 (Windows NT 10.0; WOW64; rv:47.0) Gecko/20100101 Firefox/47.0

**Comment by NielsLeenheer** [comment] 2016-08-16 18:40
I'm not able to reproduce this one. 
BTW, the user agent string is not Edge, but Firefox 47 running on Windows 10.

**Comment by NielsLeenheer** [comment] 2016-08-17 22:10
Closing this for now. If you have any more information to add, please reopen it.

**Closed by NielsLeenheer** 2016-08-17 22:10 UTC
